//! Re-exports of every crate the attribute macros expand into.
//!
//! Code generated by `#[get]`, `#[post]`, `#[patch]`, `#[delete]` and
//! `#[http_server]` is emitted into the *user's* crate, so every path it
//! mentions must resolve there. Downstream users only depend on
//! `embedded_web_server`, so the macros reach these through this crate rather
//! than requiring users to add each one to their own `Cargo.toml`.
//!
//! None of these are unused — removing one breaks macro expansion downstream.

pub use rcgen;
pub use rustls;
pub use tokio;
pub use tokio_rustls;

/// Registers route handlers at startup; used by the generated `#[ctor::ctor]` fn.
pub use ctor;

/// Deserializes non-primitive handler arguments in the generated code.
pub use serde_json;

/// Request parsing, routing table and response formatting used by every handler.
pub use utils;

pub use macros::*;
pub use utils::*;
